name: Unit Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  tests:
    name: Swift ${{ matrix.swift }} on ${{ matrix.platform }}
    strategy:
      matrix:
        platform: ['macOS', 'iOS']
        swift: ["5.7", "5.8"]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test
